apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: inventory-api
  description: Inventory Management API
  tags:
    - nodejs
    - api
    - microservice
    - mongodb
  links:
    - url: https://inventory-api.example.com/docs
      title: API Documentation
      icon: docs
    - url: https://grafana.example.com/d/inventory-dashboard
      title: Monitoring Dashboard
      icon: dashboard
    - url: https://github.com/company/inventory-api
      title: Source Code
      icon: github
    - url: https://inventory-api.example.com/health
      title: Health Check
      icon: check
    - url: https://slack.com/channels/team-inventory
      title: Team Channel
      icon: chat
    - url: https://jira.example.com/projects/INV
      title: Project Board
      icon: work
    - url: https://inventory-api.example.com
      title: Production API
      icon: web
    - url: https://runbook.example.com/inventory-api
      title: Runbook
      icon: help
  annotations:
    backstage.io/source-template: template:default/nodejs-microservice-template
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: company/inventory-api
    backstage.io/kubernetes-id: inventory-api
    backstage.io/kubernetes-namespace: production
    prometheus.io/rule: inventory-api-alerts
    sonarqube.org/project-key: inventory-api
    jenkins.io/job-full-name: company/inventory-api/main
spec:
  type: service
  lifecycle: production
  owner: team-platform
  system: e-commerce-platform
  dependsOn: 
    - 'resource:inventory-db'
    - 'component:auth-service'
    - 'component:notification-service'
  providesApis: 
    - 'api:inventory-api-v1'
  consumesApis:
    - 'api:user-service-v1'
    - 'api:payment-service-v1'
